---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: hello-world
spec:
  tykExtension:
    name: Operator hello world
    listenPath: /operator-hello-world-KD
    upstream:
      url: http://httpbin
    server:
      listenPath:
        value: /operator-hello-world-KD
        strip: true
    info:
      name: Operator hello world
      version: "1.0.0"
  oas:
    openapi: "3.0.3"
    info:
      title: Operator hello world
      version: "1.0.0"
    paths: {}
    servers:
      - url: http://httpbin