apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-oas
  namespace: tyk-demo
data:
  openapi.yaml: |
    openapi: 3.0.3
    info:
      title: Operator hello world
      version: 1.0.0
    servers:
      - url: http://httpbin
    paths:
      /get:
        get:
          responses:
            "200":
              description: OK
    x-tyk-api-gateway:
      info:
        name: Operator hello world
        state:
          active: true
      server:
        listenPath:
          value: /operator-hello-world
          strip: true
      upstream:
        url: http://httpbin
---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: hello-world-oas
  namespace: tyk-demo
spec:
  tykOAS:
    configmapRef:
      name: hello-world-oas
      keyName: openapi.yaml
